#!/usr/bin/env bash
set -Eeuo pipefail

config_file="postgresql.auto.conf"

setup_pg_hba_conf() {
    local pg_hba_file="$PGDATA/pg_hba.conf"
    local hba_entry="host    all             all             0.0.0.0/0               scram-sha-256"
    
    # Проверяем, существует ли уже такая строка
    if ! grep -q "0.0.0.0/0.*scram-sha-256" "$pg_hba_file" 2>/dev/null; then
        echo "$hba_entry" >> "$pg_hba_file"
        chmod 600 "$pg_hba_file"    
    fi
}


# RUN as root
docker_create_db_directories() {  
  rm -rf $PGDATA
  mkdir -p "$PGDATA"  
  chmod 00700 -R "$PGDATA"
  chown 999:999 -R "$PGDATA" 
  mkdir -p /var/run/postgresql
  chmod 03775 -R /var/run/postgresql
  chown 999:999 -R /var/run/postgresql  
  PG_PASSWORD=${PG_PASSWORD:-1Qwerty2}
  echo "$PG_PASSWORD" > /tmp/pw.txt
  chmod 600 /tmp/pw.txt
  chown 999:999 -R /tmp/pw.txt
  su - postgres -c "/app/bin/initdb -D $PGDATA -A scram-sha-256 --pwfile=/tmp/pw.txt"
  rm /tmp/pw.txt  
  touch "$PGDATA/$config_file"
  chmod 00700 -R "$PGDATA/$config_file"
  chown 999:999 -R "$PGDATA/$config_file" 
}

calculate_postgresql_params() {
    local mem_mb=$(awk '/MemAvailable/ {print int($2 / 1024)}' /proc/meminfo)
    if [ -z "$PG_SHARED_BUFFERS" ]; then                
        PG_SHARED_BUFFERS=$((mem_mb / 4))
        [ $PG_SHARED_BUFFERS -lt 40 ] && PG_SHARED_BUFFERS=40
        [ $PG_SHARED_BUFFERS -gt 40000 ] && PG_SHARED_BUFFERS=40000
    fi
    if [ -z "$PG_EFFECTIVE_CACHE_SIZE" ]; then
        PG_EFFECTIVE_CACHE_SIZE=$((mem_mb * 3 / 4))
    fi
    PG_MAX_CONNECTIONS=${PG_MAX_CONNECTIONS:-100}
    if [ -z "$PG_WORK_MEM" ]; then
        PG_WORK_MEM=$((($mem_mb - $PG_SHARED_BUFFERS) / ($PG_MAX_CONNECTIONS * 2)))
        [ $PG_WORK_MEM -lt 4 ] && PG_WORK_MEM=4
    fi
    if [ -z "$PG_MAINTENANCE_WORK_MEM" ]; then
        PG_MAINTENANCE_WORK_MEM=$((PG_SHARED_BUFFERS / 4))
        [ $PG_MAINTENANCE_WORK_MEM -gt 2048 ] && PG_MAINTENANCE_WORK_MEM=2048
    fi
        echo "=== Generating PostgreSQL Auto-Configuration ==="
    echo "max_connections: $PG_MAX_CONNECTIONS"
    echo "shared_buffers: ${PG_SHARED_BUFFERS}MB"
    echo "effective_cache_size: ${PG_EFFECTIVE_CACHE_SIZE}MB"
    echo "work_mem: ${PG_WORK_MEM}MB"
    echo "maintenance_work_mem: ${PG_MAINTENANCE_WORK_MEM}MB"
    echo "=============================================="
        
    cat > "$PGDATA/$config_file" << EOF
# PostgreSQL Auto-Configuration
# Generated by docker-entrypoint.sh
# DO NOT EDIT MANUALLY 11111

max_connections = ${PG_MAX_CONNECTIONS}
shared_buffers = ${PG_SHARED_BUFFERS}MB
effective_cache_size = ${PG_EFFECTIVE_CACHE_SIZE}MB
work_mem = ${PG_WORK_MEM}MB
maintenance_work_mem = ${PG_MAINTENANCE_WORK_MEM}MB
listen_addresses = '*'
port = 5432
ssl = off
shared_preload_libraries = 'timescaledb'
EOF

}

add_include_to_postgresql_conf() {
    local postgresql_conf="$PGDATA/postgresql.conf"
    
    # Проверить наличие include директивы
    if ! grep -q "^include = '$config_file'" "$postgresql_conf"; then
        echo "" >> "$postgresql_conf"
        echo "# Include auto-generated configuration" >> "$postgresql_conf"
        echo "include = '$config_file'" >> "$postgresql_conf"
    fi
}

docker_setup_env() {  
  if [ -s "$PGDATA/$config_file" ]; then
    DATABASE_ALREADY_EXISTS='true'
  else
    docker_create_db_directories
  fi
}
docker_setup_env
calculate_postgresql_params
add_include_to_postgresql_conf
setup_pg_hba_conf
exec su - postgres -c "/app/bin/postgres -D $PGDATA"
